### ISSUE TITLE
Error with sveltekit/vite $PathNode is not a function

### ISSUE THREAD

**Issue by jnicklas** [edgedb/edgedb-js#268]
I was playing around with using edgedb from sveltekit and ran into this error that I can't really make sense of:

```
8:11:17 PM [vite] Error when evaluating SSR module /dbschema/edgeql-js/modules/cfg.ts:
TypeError: __vite_ssr_import_1__.syntax.$PathNode is not a function
    at /Users/jonas/Projects/calcount/dbschema/edgeql-js/modules/cfg.ts:22:116
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async instantiateModule (/Users/jonas/Projects/calcount/node_modules/vite/dist/node/chunks/dep-971d9e33.js:56177:9)
8:11:17 PM [vite] Error when evaluating SSR module /dbschema/edgeql-js/modules/std.ts:
TypeError: __vite_ssr_import_1__.syntax.$PathNode is not a function
    at /Users/jonas/Projects/calcount/dbschema/edgeql-js/modules/cfg.ts:22:116
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async instantiateModule (/Users/jonas/Projects/calcount/node_modules/vite/dist/node/chunks/dep-971d9e33.js:56177:9)
8:11:17 PM [vite] Error when evaluating SSR module /dbschema/edgeql-js/syntax/setImpl.ts:
TypeError: __vite_ssr_import_1__.syntax.$PathNode is not a function
    at /Users/jonas/Projects/calcount/dbschema/edgeql-js/modules/cfg.ts:22:116
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async instantiateModule (/Users/jonas/Projects/calcount/node_modules/vite/dist/node/chunks/dep-971d9e33.js:56177:9)
8:11:17 PM [vite] Error when evaluating SSR module /dbschema/edgeql-js/syntax/set.ts:
...
```

I've put this code on GitHub here: https://github.com/jnicklas/edgedbsveltekit

**Comment by pheuter** [comment]
A workaround in the meantime that I use is to generate the query builder as esm: `edgeql-js --target esm`.
