### ISSUE TITLE
"[Errno 2] No such file or directory" when running any query.

### ISSUE THREAD

**Issue by cdiezmoran** [edgedb/edgedb-js#343]
I'm very new to EdgeDB so I hope I'm providing all the info you need for this issue.

My implementation was working at first and suddenly I started getting this issue whenever I run an EdgeDB query:
```
InternalServerError: [Errno 2] No such file or directory
    at RawConnection._parseErrorMessage (/Users/lits/Dev/feather-fastify/node_modules/edgedb/dist/baseConn.js:280:21)
    at RawConnection._executeFlow (/Users/lits/Dev/feather-fastify/node_modules/edgedb/dist/baseConn.js:587:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RawConnection.fetch (/Users/lits/Dev/feather-fastify/node_modules/edgedb/dist/baseConn.js:716:17)
    at async ClientConnectionHolder.retryingFetch (/Users/lits/Dev/feather-fastify/node_modules/edgedb/dist/client.js:178:26)
    at async Client.query (/Users/lits/Dev/feather-fastify/node_modules/edgedb/dist/client.js:468:20)
    at async exports.default (/Users/lits/Dev/feather-fastify/src/initialize.ts:9:18) {
  source: undefined
}
```

I'm running it like this:
```
import { createClient } from 'edgedb';

const db = createClient();

const result = await db.query('select "Hello world";');
console.log(result);
```

The version of edgedb in my `package.json` is:
```
"edgedb": "^0.20.9"
```
You can check out the project for the backend I'm getting this issue on [here](https://github.com/cdiezmoran/feather-fastify/tree/remake).

Any ideas you have on how to fix this would be really appreciated, thank you in advance!

**Comment by elprans** [comment]
Interesting.  Can you attach your instance logs please?  `edgedb instance logs <your-instance-name>`.  You can get the name of the DB instance by running `edgedb project info --instance-name`.  Thanks!

**Comment by cdiezmoran** [comment]
I'm getting this error when I try to access the logs of my instance:
```
tail: /Users/lits/Library/Caches/edgedb/logs/feather.log: No such file or directory
```
When I saw that I realized that I deleted almost all of the folders in my Caches folder to make space for the new Xcode version 🙃 do you think EdgeDB might be trying to access a file on the Caches folder that isn't there anymore?

**Comment by elprans** [comment]
Hm, there is nothing critical in `Cache` afaik.  Does `edgedb` CLI work?

**Comment by cdiezmoran** [comment]
I just tried to do a migration and the CLI is not working, I'm getting the same no such file or directory issue:
```
❯ edgedb migration create
edgedb error: InternalServerError: [Errno 2] No such file or directory
  Hint: This is most likely a bug in EdgeDB. Please consider opening an issue ticket at https://github.com/edgedb/edgedb/issues/new?template=bug_report.md
  Server traceback:
      Traceback (most recent call last):
        File "edb/server/protocol/binary.pyx", line 1849, in edb.server.protocol.binary.EdgeConnection.main
        File "edb/server/protocol/binary.pyx", line 1716, in execute
        File "edb/server/protocol/binary.pyx", line 1612, in _execute
        File "edb/server/protocol/binary.pyx", line 295, in get_pgcon
        File "edb/server/protocol/binary.pyx", line 289, in edb.server.protocol.binary.EdgeConnection.get_pgcon
        File "/Users/lits/Library/Application Support/edgedb/portable/1.0-rc.5/lib/python3.10/site-packages/edb/server/server.py", line 512, in acquire_pgcon
          conn = await self._pg_pool.acquire(dbname)
        File "/Users/lits/Library/Application Support/edgedb/portable/1.0-rc.5/lib/python3.10/site-packages/edb/server/connpool/pool.py", line 1126, in acquire
          conn = await self._acquire(dbname)
        File "/Users/lits/Library/Application Support/edgedb/portable/1.0-rc.5/lib/python3.10/site-packages/edb/server/connpool/pool.py", line 1079, in _acquire
          return await block.acquire()
        File "/Users/lits/Library/Application Support/edgedb/portable/1.0-rc.5/lib/python3.10/site-packages/edb/server/connpool/pool.py", line 258, in acquire
          await waiter
        File "/Users/lits/Library/Application Support/edgedb/portable/1.0-rc.5/lib/python3.10/site-packages/edb/server/connpool/pool.py", line 514, in _connect
          conn = await self._connect_cb(block.dbname)
        File "/Users/lits/Library/Application Support/edgedb/portable/1.0-rc.5/lib/python3.10/site-packages/edb/server/server.py", line 326, in _pg_connect
          rv = await pgcon.connect(
        File "edb/server/pgcon/pgcon.pyx", line 322, in connect
        File "edb/server/pgcon/pgcon.pyx", line 253, in _connect
        File "uvloop/loop.pyx", line 2260, in create_unix_connection
        File "uvloop/loop.pyx", line 2255, in uvloop.loop.Loop.create_unix_connection
      FileNotFoundError: [Errno 2] No such file or directory

**Comment by cdiezmoran** [comment]
Some parts of the CLI are working for example running `edgedb project init` works without any issues. I tried re-installing the CLI but I still get the issue on my project with queries and `edgedb migration create`.

**Comment by elprans** [comment]
Try `edgedb instance restart $(edgedb project info --instance-name)`

**Comment by cdiezmoran** [comment]
That fixed it thank you!
