### ISSUE TITLE
cardinality.ts compile error

### ISSUE THREAD

**Issue by NexZhu** [edgedb/edgedb-js#516]
**Code**
The code causing the error.

TypeScript version: 4.8.4

Compile error:
```
TSError: ⨯ Unable to compile TypeScript:
src/edgedb/generated/edgeql-js/cardinality.ts:167:62 - error TS2345: Argument of type 'Cardinality | undefined' is not assignable to parameter of type 'Cardinality'.
  Type 'undefined' is not assignable to type 'Cardinality'.

167     if (cards.length === 2) return mergeCardinalities(first, second) as any;
                                                                 ~~~~~~
src/edgedb/generated/edgeql-js/cardinality.ts:169:33 - error TS2345: Argument of type 'Cardinality | undefined' is not assignable to parameter of type 'Cardinality'.

169       mergeCardinalities(first, second),
                                    ~~~~~~

    at createTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2345, 2345 ]
```

My `tsconfig.json`:

```js
{
  "extends": "./node_modules/@daotl/tsconfig/node.json",
  "compilerOptions": {
    "outDir": "./dist",
    "baseUrl": ".",
    "paths": {
      "~/*": ["src/*"]
    },
    "module": "CommonJS",
    "moduleResolution": "Node",
    "noPropertyAccessFromIndexSignature": false
  },
  "reflection": true
}
```

`node_modules/@daotl/tsconfig/node.json`:
```js
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Base",

  "compilerOptions": {
    "module": "ESNext",
    "target": "ESNext",
    "useDefineForClassFields": true,
    "lib": [
      "ESNext",
      "ESNext.AsyncIterable"
    ],
    "resolveJsonModule": true,
    "newLine": "lf",
    "removeComments": true,
    "stripInternal": true,
    "allowJs": true,
    "incremental": true,

    /* Strict Type-Checking Options */
    "strict": true,                              /* Enable all strict type-checking options. */
    "noImplicitAny": true,                       /* Raise error on expressions and declarations with an implied 'any' type. */
    "strictNullChecks": true,                    /* Enable strict null checks. */
    "strictFunctionTypes": true,                 /* Enable strict checking of function types. */
    "strictBindCallApply": true,                 /* Enable strict 'bind', 'call', and 'apply' methods on functions. */
    "strictPropertyInitialization": true,        /* Enable strict checking of property initialization in classes. */
    "noImplicitThis": true,                      /* Raise error on 'this' expressions with an implied 'any' type. */
    "alwaysStrict": true,                        /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // Check with ESLint 'no-unused-vars' rule
    // "noUnusedLocals": true,                      /* Report errors on unused locals. */
    // "noUnusedParameters": true,                  /* Report errors on unused parameters. */
    "noImplicitReturns": true,                   /* Report error when not all code paths in function return a value. */
    "noFallthroughCasesInSwitch": true,          /* Report errors for fallthrough cases in switch statement. */
    "noUncheckedIndexedAccess": true,            /* Include 'undefined' in index signature results */
    "noImplicitOverride": true,                  /* Ensure overriding members in derived classes are marked with an 'override' modifier. */
    "noPropertyAccessFromIndexSignature": true,  /* Require undeclared properties from index signatures to use element accesses. */

    /* Module Resolution Options */
    "moduleResolution": "node",                  /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    // Following path related configs are disabled because of https://github.com/Microsoft/TypeScript/issues/29172
    // "baseUrl": "./",                             /* Base directory to resolve non-absolute module names. */
    // "paths": {},                                 /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                              /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                             /* List of folders to include type definitions from. */
    // "types": [],                                 /* Type declaration files to be included in compilation. */
    "allowSyntheticDefaultImports": true,        /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true,                        /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,                    /* Do not resolve the real path of symlinks. */
    // "allowUmdGlobalAccess": true,                /* Allow accessing UMD globals from modules. */

    /* Source Map Options */
    "sourceMap": true,
    // "sourceRoot": "",                            /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                               /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,                     /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                       /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    "experimentalDecorators": true,              /* Enables experimental support for ES7 decorators. */
    "emitDecoratorMetadata": true,               /* Enables experimental support for emitting type metadata for decorators. */

    /* Advanced Options */
    "skipLibCheck": true,                           /* Skip type checking of declaration files. */
    "forceConsistentCasingInFileNames": true        /* Disallow inconsistently-cased references to the same file. */
  }
}
```

- OS: WSL2 Centos 9
- EdgeDB version: `2.9`
- `@edgedb/generate` version: `0.0.7`
- Typescript version: 4.8.4
- Node/Deno version: 19.3.0

**Comment by NexZhu** [comment]
Similar issue in `collection.ts`
```
/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/edgedb/generated/edgeql-js/collections.ts:160:28 - error TS2532: Object is possibly 'undefined'.

160         __name__: `array<${items[0].__element__.__name__}>`,
                               ~~~~~~~~
src/edgedb/generated/edgeql-js/collections.ts:161:22 - error TS2532: Object is possibly 'undefined'.

161         __element__: items[0].__element__
                         ~~~~~~~~
src/edgedb/generated/edgeql-js/collections.ts:289:24 - error TS2532: Object is possibly 'undefined'.

289       typeShape[key] = exprShape[key].__element__;
                           ~~~~~~~~~~~~~~

    at createTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2532, 2532, 2532 ]
}
```

**Comment by NexZhu** [comment]
Similar issues in `toEdgeQL.ts`
```
/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/edgedb/generated/edgeql-js/toEdgeQL.ts:892:13 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

892             expr.__shape__[key],
                ~~~~~~~~~~~~~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1134:34 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

1134             index = renderEdgeQL(args[1], ctx);
                                      ~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1137:34 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

1137           return `${renderEdgeQL(args[0], ctx)}[${index}]`;
                                      ~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1139:33 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

1139         return `(${renderEdgeQL(args[0], ctx)} ${operator} ${renderEdgeQL(
                                     ~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1140:11 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

1140           args[1],
               ~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1144:33 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

1144         return `(${renderEdgeQL(args[0], ctx)} ${operator})`;
                                     ~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1146:45 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

1146         return `(${operator} ${renderEdgeQL(args[0], ctx)})`;
                                                 ~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1149:35 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

1149           return `(${renderEdgeQL(args[0], ctx)} IF ${renderEdgeQL(
                                       ~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1150:13 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

1150             args[1],
                 ~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1152:34 - error TS2345: Argument of type 'TypeSet<BaseType, Cardinality> | undefined' is not assignable to parameter of type 'TypeSet<BaseType, Cardinality>'.
  Type 'undefined' is not assignable to type 'TypeSet<BaseType, Cardinality>'.

1152           )} ELSE ${renderEdgeQL(args[2], ctx)})`;
                                      ~~~~~~~
src/edgedb/generated/edgeql-js/toEdgeQL.ts:1506:40 - error TS2345: Argument of type 'BaseType | undefined' is not assignable to parameter of type 'BaseType'.
  Type 'undefined' is not assignable to type 'BaseType'.

1506           `${key} := ${literalToEdgeQL(type.__shape__[key], value)}`
                                            ~~~~~~~~~~~~~~~~~~~

    at createTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [
    2345, 2345, 2345,
    2345, 2345, 2345,
    2345, 2345, 2345,
    2345, 2345
  ]
}
```

**Comment by NexZhu** [comment]
Similar issues in `json.ts`
```
TSError: ⨯ Unable to compile TypeScript:
src/edgedb/generated/edgeql-js/select.ts:498:15 - error TS2532: Object is possibly 'undefined'.

498               (root.__element__ as any as ObjectType)["__pointers__"][key][
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2532 ]
```

**Comment by NexZhu** [comment]
Similar issue in `hydrate.ts`
```
TSError: ⨯ Unable to compile TypeScript:
src/edgedb/generated/edgeql-js/hydrate.ts:181:9 - error TS2532: Object is possibly 'undefined'.

181     if (type.tuple_elements[0].name === "0") {
            ~~~~~~~~~~~~~~~~~~~~~~
src/edgedb/generated/edgeql-js/hydrate.ts:266:35 - error TS2532: Object is possibly 'undefined'.

266         if (aitem.cardinality !== bitem.cardinality) continue;
                                      ~~~~~
src/edgedb/generated/edgeql-js/hydrate.ts:268:39 - error TS2532: Object is possibly 'undefined'.

268         if (aitem.target.__name__ !== bitem.target.__name__) continue;
                                          ~~~~~

    at createTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2532, 2532, 2532 ]
```

**Comment by NexZhu** [comment]
Similar issues in `insert.ts`:
```
TSError: ⨯ Unable to compile TypeScript:
src/edgedb/generated/edgeql-js/insert.ts:215:42 - error TS2532: Object is possibly 'undefined'.

215         newShape[key] = (literal as any)(pointer.target, val.__value__);
                                             ~~~~~~~
src/edgedb/generated/edgeql-js/insert.ts:231:9 - error TS2532: Object is possibly 'undefined'.

231     if (pointer.__kind__ !== "property" && val !== null) {
            ~~~~~~~
src/edgedb/generated/edgeql-js/insert.ts:242:7 - error TS2532: Object is possibly 'undefined'.

242       pointer.cardinality === Cardinality.AtLeastOne ||
          ~~~~~~~
src/edgedb/generated/edgeql-js/insert.ts:243:7 - error TS2532: Object is possibly 'undefined'.

243       pointer.cardinality === Cardinality.Many;
          ~~~~~~~
src/edgedb/generated/edgeql-js/insert.ts:244:9 - error TS2532: Object is possibly 'undefined'.

244     if (pointer.__kind__ === "property") {
            ~~~~~~~
src/edgedb/generated/edgeql-js/insert.ts:245:11 - error TS2532: Object is possibly 'undefined'.

245       if (pointer.target.__name__ === "std::json") {
              ~~~~~~~
src/edgedb/generated/edgeql-js/insert.ts:251:16 - error TS2532: Object is possibly 'undefined'.

251         ? cast(pointer.target, null)
                   ~~~~~~~
src/edgedb/generated/edgeql-js/insert.ts:254:18 - error TS2532: Object is possibly 'undefined'.

254           ? cast(pointer.target, null)
                     ~~~~~~~
src/edgedb/generated/edgeql-js/insert.ts:255:50 - error TS2532: Object is possibly 'undefined'.

255           : set(...val.map(v => (literal as any)(pointer.target, v)))
                                                     ~~~~~~~
src/edgedb/generated/edgeql-js/insert.ts:256:28 - error TS2532: Object is possibly 'undefined'.

256         : (literal as any)(pointer.target, val);
                               ~~~~~~~

    at createTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [
    2532, 2532, 2532,
    2532, 2532, 2532,
    2532, 2532, 2532,
    2532
  ]
}
```

**Comment by NexZhu** [comment]
Similar issue in `group.ts`
```
TSError: ⨯ Unable to compile TypeScript:
src/edgedb/generated/edgeql-js/group.ts:203:29 - error TS2538: Type 'undefined' cannot be used as an index type.

203   const grouping = groupSet[key] as any as GroupingSet;
                                ~~~

    at createTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2538 ]
}
```

**Comment by NexZhu** [comment]
`funcopts.ts`
```
TSError: ⨯ Unable to compile TypeScript:
src/edgedb/generated/edgeql-js/funcops.ts:333:9 - error TS2322: Type '(string | undefined)[]' is not assignable to type 'string[]'.
  Type 'string | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.

333   const descendants: string[] = [
            ~~~~~~~~~~~
src/edgedb/generated/edgeql-js/funcops.ts:412:30 - error TS2532: Object is possibly 'undefined'.

412           ptrTarget.name !== argPtr.target.__name__ ||
                                 ~~~~~~
src/edgedb/generated/edgeql-js/funcops.ts:413:24 - error TS2532: Object is possibly 'undefined'.

413           ptr.card !== argPtr.cardinality
                           ~~~~~~
src/edgedb/generated/edgeql-js/funcops.ts:437:27 - error TS2532: Object is possibly 'undefined'.

437           if (keys[i] !== type.tuple_elements[i].name) {
                              ~~~~~~~~~~~~~~~~~~~~~~
src/edgedb/generated/edgeql-js/funcops.ts:442:13 - error TS2532: Object is possibly 'undefined'.

442             type.tuple_elements[i].target_id,
                ~~~~~~~~~~~~~~~~~~~~~~
src/edgedb/generated/edgeql-js/funcops.ts:443:28 - error TS2538: Type 'undefined' cannot be used as an index type.

443             (items as any)[keys[i]]
                               ~~~~~~~

    at createTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2322, 2532, 2532, 2532, 2532, 2538 ]
}

**Comment by NexZhu** [comment]
`operators.ts`
```
TSError: ⨯ Unable to compile TypeScript:
src/edgedb/generated/edgeql-js/operators.ts:4048:9 - error TS2322: Type 'any[] | undefined' is not assignable to type 'any[] | null'.
  Type 'undefined' is not assignable to type 'any[] | null'.

4048         defs = overloadDefs.Prefix[op];
             ~~~~
src/edgedb/generated/edgeql-js/operators.ts:4052:9 - error TS2322: Type 'any[] | undefined' is not assignable to type 'any[] | null'.

4052         defs = overloadDefs.Postfix[op];
             ~~~~
src/edgedb/generated/edgeql-js/operators.ts:4058:9 - error TS2322: Type 'any[] | undefined' is not assignable to type 'any[] | null'.

4058         defs = overloadDefs.Infix[op];
             ~~~~
src/edgedb/generated/edgeql-js/operators.ts:4064:9 - error TS2322: Type 'any[] | undefined' is not assignable to type 'any[] | null'.

4064         defs = overloadDefs.Ternary[op];
             ~~~~

    at createTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/root/dev/web/daotl-deepkit-starter/node_modules/.pnpm/ts-node@10.9.1_vqcafhj4xvr2nzknlrdklk55zm/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  diagnosticCodes: [ 2322, 2322, 2322, 2322 ]
}
```

**Comment by NexZhu** [comment]
Example of the modifications needed to generated `edgeql-js` code to make it run with strict TS type check:
https://github.com/daotl/deepkit-starter/commit/e0e673710dad26678e144a87c00ad66366efe9b9
