### ISSUE TITLE
filter_single not working

### ISSUE THREAD

**Issue by fillon** [edgedb/edgedb-js#519]
**Describe the bug**
Typescript returning: 

```
No overload matches this call.
  Overload 1 of 6, '(expr: $expr_PathNode<TypeSet<$Currency, Cardinality.Many>, null>, shape: (scope: { __element__: $Currency; __cardinality__: Cardinality.One; __parent__: PathParent<...> | null; __kind__: ExpressionKind.PathNode; "*": { ...; }; } & { ...; } & {} & ExpressionMethods<...> & { ...; }) => Readonly<...>): $expr_Select<...>', gave the following error.
    Type '{ code: string; }' is not assignable to type 'SelectFilterExpression | { id: orLiteralValue<{ __element__: $uuid; __cardinality__: Cardinality.One; }>; } | undefined'.
      Object literal may only specify known properties, and 'code' does not exist in type 'SelectFilterExpression | { id: orLiteralValue<{ __element__: $uuid; __cardinality__: Cardinality.One; }>; }'.
  Overload 2 of 6, '(expr: PrimitiveTypeSet, modifiers: (expr: PrimitiveTypeSet) => Readonly<SelectModifiers<ObjectType<string, ObjectTypePointers, any, ExclusiveTuple>>>): $expr_Select<...>', gave the following error.
    Argument of type '$expr_PathNode<TypeSet<$Currency, Cardinality.Many>, null>' is not assignable to parameter of type 'PrimitiveTypeSet'.
      Types of property '__element__' are incompatible.
        Type '$Currency' is not assignable to type 'PrimitiveType'.
          Type 'ObjectType<"default::Currency", { __type__: LinkDesc<$ObjectType, Cardinality.One, {}, false, false, true, false>; id: PropertyDesc<$uuid, Cardinality.One, true, false, true, true>; code: PropertyDesc<...>; decimal: PropertyDesc<...>; "<currency[is Book]": LinkDesc<...>; "<currency": LinkDesc<...>; }, null, [...]>' is not assignable to type 'NamedTupleType<NamedTupleShape>'.
            Types of property '__kind__' are incompatible.
              Type 'TypeKind.object' is not assignable to type 'TypeKind.namedtuple'.
```

**Reproduction**
Include the code that is causing the error:

```typescript
let cs = await e
        .select(e.Currency, () => ({
            code: true,
            decimal: true,

            filter_single: { code: 'USD' },
        }))
        .run(client);
```

**Expected behavior**
Return a single object.
```
    type Currency {
        required property code -> str;
        required property decimal -> int32;
    }
```

**Versions (please complete the following information):**

- OS:
- EdgeDB version (e.g. `2.0`): 2
- EdgeDB CLI version (e.g. `2.0`): 2.2.6+7eabbf9
- `edgedb-js` version (e.g. `0.20.10`;): 1.0.2
- `@edgedb/generate`: 0.0.7
- Node/Deno version: node 18.12.1
- typescript: 4.9.4
- tsx: 7.1.1

**Additional context**
Output from running the script.

```
/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseConn.js:310
        const err = new errorType(message);
                    ^


ResultCardinalityMismatchError: the query has cardinality MANY which does not match the expected cardinality ONE
    at RawConnection._parseErrorMessage (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseConn.js:310:21)
    at RawConnection._executeFlow (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseConn.js:918:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RawConnection.fetch (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseConn.js:970:17)
    at ClientConnectionHolder.retryingFetch (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseClient.js:178:26)
    at Client.querySingle (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseClient.js:505:20)
    at main (/Volumes/SSD1T/Users/stephane/dev/boki/scripts/seed.ts:61:14) {
  source: undefined
}

Node.js v18.12.1
file:///Volumes/SSD1T/Users/stephane/dev/boki/node_modules/zx/build/core.js:146
            let output = new ProcessOutput(code, signal, stdout, stderr, combined, message);
                         ^

ProcessOutput [Error]: /Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseConn.js:310
        const err = new errorType(message);
                    ^


ResultCardinalityMismatchError: the query has cardinality MANY which does not match the expected cardinality ONE
    at RawConnection._parseErrorMessage (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseConn.js:310:21)
    at RawConnection._executeFlow (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseConn.js:918:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at RawConnection.fetch (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseConn.js:970:17)
    at ClientConnectionHolder.retryingFetch (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseClient.js:178:26)
    at Client.querySingle (/Volumes/SSD1T/Users/stephane/dev/boki/node_modules/edgedb/dist/baseClient.js:505:20)
    at main (/Volumes/SSD1T/Users/stephane/dev/boki/scripts/seed.ts:61:14) {
  source: undefined
```

**Comment by NurbekGithub** [comment]
I encountered the same issue today
```
OS: macOS 12.5
EdgeDB version (e.g. 2.0): 2.3
EdgeDB CLI version (e.g. 2.0): 2.2.6+7eabbf9
edgedb-js version (e.g. 0.20.10;): 1.0.2
@edgedb/generate:
Node/Deno version: node 18.12.1
typescript: 4.8.4
tsx:
```

**Comment by NurbekGithub** [comment]
update:
It works now as I added constraint exclusive to the field. (Had to get rid of some duplicate rows tho)
