### ISSUE TITLE
`pnpm dlx @edgedb/generate` not working

### ISSUE THREAD

**Issue by devunt** [edgedb/edgedb-js#567]
**Describe the bug**
While `npx @edgedb/generate` is working as expected, `pnpm dlx @edgedb/generate` is not working with following errors.

```
~/w/rezero develop• 6.5s [1] pnpm dlx @edgedb/generate
../../Library/pnpm/store/v3/tmp/dlx-6039 |  +16 ++
 WARN  Issues with peer dependencies found
.
└─┬ @edgedb/generate 0.0.8
  └── ✕ missing peer edgedb@^1.0.0-alpha.0
Peer dependencies that should be installed:
  edgedb@^1.0.0-alpha.0  

../../Library/pnpm/store/v3/tmp/dlx-6039 | Progress: resolved 16, reused 16, downloaded 0, added 16, done
node:internal/modules/cjs/loader:1093
  throw err;
  ^

Error: Cannot find module 'edgedb'
Require stack:
- /Users/devunt/Library/pnpm/store/v3/tmp/dlx-6039/node_modules/.pnpm/@edgedb+generate@0.0.8/node_modules/@edgedb/generate/dist/cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Module._load (node:internal/modules/cjs/loader:934:27)
    at Module.require (node:internal/modules/cjs/loader:1157:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/Users/devunt/Library/pnpm/store/v3/tmp/dlx-6039/node_modules/.pnpm/@edgedb+generate@0.0.8/node_modules/@edgedb/generate/dist/cli.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/devunt/Library/pnpm/store/v3/tmp/dlx-6039/node_modules/.pnpm/@edgedb+generate@0.0.8/node_modules/@edgedb/generate/dist/cli.js'
  ]
}

Node.js v19.8.1
 ERROR  Command failed with exit code 1: generate

pnpm: Command failed with exit code 1: generate
    at makeError (/Users/devunt/Library/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:24230:17)
    at handlePromise (/Users/devunt/Library/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:24801:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler [as dlx] (/Users/devunt/Library/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:215154:7)
    at async /Users/devunt/Library/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:222970:21
    at async main (/Users/devunt/Library/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:222937:34)
    at async runPnpm (/Users/devunt/Library/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:223192:5)
    at async /Users/devunt/Library/pnpm/global/5/.pnpm/pnpm@7.30.3/node_modules/pnpm/dist/pnpm.cjs:223184:7
```

**Reproduction**
```
$ pnpm dlx @edgedb/generate edgeql-js
```

**Expected behavior**
Command runs.

**Versions (please complete the following information):**
- OS: `macOS 13.2.1 (Apple M1 Pro)`
- EdgeDB version: `2.12+4727bd2`
- EdgeDB CLI version: `2.3.1+5d93f42`
- `edgedb-js` version: `1.1.0`
- Node/Deno version: `v19.8.1`
- pnpm version: `7.30.3`

**Additional context**
Nothing

**Comment by scotttrinh** [comment]
Thanks for the heads-up! We'll publish a new version that fixes the peer dependency issue in the next few days.

**Comment by scotttrinh** [comment]
Fixed in v1.2.0+

**Comment by notramo** [comment]
@scotttrinh, it doesn't work (`edgedb@1.2.1`, `@edgedb/generate@0.1.0`).

**Comment by notramo** [comment]
@devunt, there is a workaround:
- Install it as dev dependency: `pnpm add -D @edgedb/generate`
- run `pnpm exec generate edgeql-js`
