### ISSUE TITLE
InternalServerError: relation "edgedbpub.6f1951f8-d9c5-11ed-95c3-03de6c5dab72_t" does not exist

### ISSUE THREAD

**Issue by lu-zen** [edgedb/edgedb-js#569]
- EdgeDB Version: `3.0-dev.7404+0dd672e`
- EdgeDB CLI Version: 3.0.0-dev.947+3c26302
- OS Version: endeavouros linux-lts kernel

Steps to Reproduce:

1. apply migration
2. try to generate typescript query builder:
`npx @edgedb/generate edgeql-js`

[Schema and migration](https://gist.github.com/lu-zen/315117d2c54ab5f50b1c0a23da95e789)

Error:
```
Introspecting database schema...
project/node_modules/edgedb/dist/baseConn.js:314
        const err = new errorType(message);
                    ^

InternalServerError: relation "edgedbpub.b9e05da3-d9c9-11ed-9a57-dfe9835859fc_t" does not exist
    at RawConnection._parseErrorMessage (project/node_modules/edgedb/dist/baseConn.js:314:21)
    at RawConnection._executeFlow (project/node_modules/edgedb/dist/baseConn.js:922:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RawConnection.fetch (project/node_modules/edgedb/dist/baseConn.js:974:17)
    at async ClientConnectionHolder.retryingFetch (project/node_modules/edgedb/dist/baseClient.js:182:26)
    at async Client.queryJSON (project/node_modules/edgedb/dist/baseClient.js:500:20)
    at async Object._scalars (project/node_modules/edgedb/dist/reflection/queries/scalars.js:6:25)
    at async Promise.all (index 1)
    at async generateQueryBuilder (project/node_modules/@edgedb/generate/dist/edgeql-js.js:79:81)
    at async run (project/node_modules/@edgedb/generate/dist/cli.js:267:13) {
  source: undefined
}
```

**Comment by jaclarke** [comment]
This is an `InternalServerError`, so is a bug in the edgedb compiler. It seems to be possible to work around this bug by updating the scalar introspection query to include:
```edgeql
  children := (select .<bases)[IS Type] { id, name },
```
but I'd rather wait to see if this bug can be easily fixed in the compiler first.

**Comment by lu-zen** [comment]
@jaclarke just to let you know it works fine on
edgedb server: `3.0-alpha.3+b5168d2`

edgedb: `1.2.0`
@edgedb/generate: `0.1.0`

**Comment by Ethras** [comment]
Facing the same issue with the latest 3.0 beta version

edgedb: 1.2.0
@edgedb/generate: 0.1.0

**Comment by CSFlorin** [comment]
This was happening to me because I had an older version of @edgedb/generate installed globally. Just installed it locally and that fixed it up https://www.edgedb.com/docs/clients/js/generation#installation
