### ISSUE TITLE
Setting the TLS ServerName to an IP address is not permitted by RFC 6066

### ISSUE THREAD

**Issue by MrFoxPro** [edgedb/edgedb-js#789]
**Describe the bug**
DSN: `edgedb://USER:PASSWORD@127.0.0.1:10703/dev_faundr_ru`
```
(node:104660) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
    at Object.connect (node:_tls_wrap:1796:15)
    at RawConnection.newSock (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/rawConn.js:202:35)
    at RawConnection.connectWithTimeout (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/rawConn.js:217:27)
    at retryingConnect (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/retry.js:53:26)
    at ClientPool.getNewConnection (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/baseClient.js:348:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ClientConnectionHolder._getConnection (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/baseClient.js:93:32)
    at async ClientConnectionHolder.retryingFetch (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/baseClient.js:180:26)
    at async Client.execute (/nix/store/9byc3kizaqqq3x3v1367ffppyqqfi9z1-dev_faundr_ru/api/node_modules/.pnpm/edgedb@1.4.1/node_modules/edgedb/dist/baseClient.js:482:20)
```

**Expected behavior**
Do not use deprecation methods warning

**Versions (please complete the following information):**

- OS: Linux 6.6.2-arch1-1
- EdgeDB version (e.g. `2.0`): 4.1
- EdgeDB CLI version (e.g. `2.0`): 4.1.0-dev
- `edgedb-js` version (e.g. `0.20.10`;): 1.4.1 
- Node/Deno version: Node v21.2.0

**Comment by MrFoxPro** [comment]
Warning doesn't appear if I replace 127.0.0.1 with localhost btw
