### ISSUE TITLE
Deprecated Deno APIs

### ISSUE THREAD

**Issue by NetOpWibby** [edgedb/edgedb-js#844]
**Describe the bug**
The Deno client library is using APIs that will be removed from Deno soon

**Reproduction**
Run a Deno application using EdgeDB

**Expected behavior**
No deprecation warnings

**Versions (please complete the following information):**

- OS: macOS Sonoma 14.2.1
- EdgeDB version (e.g. `2.0`): `4.4+aa576e1`
- EdgeDB CLI version (e.g. `2.0`): `4.0.2+500be79`
- Deno version: `1.40.2`

**Additional context**
```
⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
warning: Use of deprecated "Deno.stderr.rid" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
warning: Use of deprecated "Deno.isatty()" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
warning: Use of deprecated "Deno.stdout.rid" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
warning: Use of deprecated "Deno.stdin.rid" API. This API will be removed in Deno 2. Run again with DENO_VERBOSE_WARNINGS=1 to get more details.
```

**Comment by scotttrinh** [comment]
@NetOpWibby 

Do you have any idea where those four APIs are being used in the client? I wasn't able to find any references to them when I grep'd for them across the whole codebase. I wonder if they're coming from some pinned dependencies in the standard Deno library? I'll keep looking around, but I was hoping to just knock it out real quick, but no such luck.

**Comment by NetOpWibby** [comment]
Hmm, it could be possible these were from my own project but I saw these errors when running that command for regenerating the client library. Could be some other dependency I'm using. I'll check more in-depth today.

**Comment by NetOpWibby** [comment]
My apologies for the lateness! I ran my project with `DENO_VERBOSE_WARNINGS=1` and it provided a stack trace of where the issues stem from...Deno's own `std` library LOL.

**Comment by scotttrinh** [comment]
@NetOpWibby 

I assume that means it's coming from _our_ pinned versions from the `std` library. Do you mind providing some of the output from `DENO_VERBOSE_WARNINGS` so we can look into bumping our `std` dependencies. I'm going to reopen to consider this as a tracking issue for ensuring we're ready for Deno 2.

**Comment by 1st1** [comment]
> Deno's own std library LOL.

Lol indeed.

**Comment by NetOpWibby** [comment]
@scotttrinh Here you go!

```
DENO_VERBOSE_WARNINGS=1 denon start --development
⚠️  The `--unstable` flag is deprecated and will be removed in Deno 2.0. Use granular `--unstable-*` flags instead.
Learn more at: https://docs.deno.com/runtime/manual/tools/unstable_flags
[*] [main] v2.5.0
[*] [daem] watching path(s): **/*.*
[*] [daem] watching extensions: ts,tsx,js,jsx,json
[!] [#0] starting `deno run --allow-env --allow-net --allow-read --import-map import_map.json main.ts --development`
warning: Use of deprecated "Deno.stderr.rid" API. This API will be removed in Deno 2.

Stack trace:
  at createWritableStdioStream (https://deno.land/std@0.177.0/node/_process/streams.mjs:36:21)
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:94:38

hint: Use `Deno.stderr` instance methods instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.

warning: Use of deprecated "Deno.stderr.rid" API. This API will be removed in Deno 2.

Stack trace:
  at createWritableStdioStream (https://deno.land/std@0.177.0/node/_process/streams.mjs:68:27)
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:94:38

hint: Use `Deno.stderr` instance methods instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.

warning: Use of deprecated "Deno.isatty()" API. This API will be removed in Deno 2.

Stack trace:
  at createWritableStdioStream (https://deno.land/std@0.177.0/node/_process/streams.mjs:68:20)
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:94:38

hint: Use `Deno.stdin.isTerminal()`, `Deno.stdout.isTerminal()` or `Deno.stderr.isTerminal()` instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.

warning: Use of deprecated "Deno.stdout.rid" API. This API will be removed in Deno 2.

Stack trace:
  at createWritableStdioStream (https://deno.land/std@0.177.0/node/_process/streams.mjs:36:21)
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:100:38

hint: Use `Deno.stdout` instance methods instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.

warning: Use of deprecated "Deno.stdout.rid" API. This API will be removed in Deno 2.

Stack trace:
  at createWritableStdioStream (https://deno.land/std@0.177.0/node/_process/streams.mjs:68:27)
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:100:38

hint: Use `Deno.stdout` instance methods instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.

warning: Use of deprecated "Deno.isatty()" API. This API will be removed in Deno 2.

Stack trace:
  at createWritableStdioStream (https://deno.land/std@0.177.0/node/_process/streams.mjs:68:20)
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:100:38

hint: Use `Deno.stdin.isTerminal()`, `Deno.stdout.isTerminal()` or `Deno.stderr.isTerminal()` instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.

warning: Use of deprecated "Deno.stdin.rid" API. This API will be removed in Deno 2.

Stack trace:
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:164:24
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:224:3

hint: Use `Deno.stdin` instance methods instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.

warning: Use of deprecated "Deno.isatty()" API. This API will be removed in Deno 2.

Stack trace:
  at _guessStdinType (https://deno.land/std@0.177.0/node/_process/streams.mjs:110:20)
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:166:21
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:224:3

hint: Use `Deno.stdin.isTerminal()`, `Deno.stdout.isTerminal()` or `Deno.stderr.isTerminal()` instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.

warning: Use of deprecated "Deno.stdin.rid" API. This API will be removed in Deno 2.

Stack trace:
  at https://deno.land/std@0.177.0/node/_process/streams.mjs:226:22

hint: Use `Deno.stdin` instance methods instead.
hint: It appears this API is used by a remote dependency. Try upgrading to the latest version of that dependency.
```

**Comment by NetOpWibby** [comment]
Tagging onto this issue to state that the query builder doesn't know about branches yet. Also, the repo for the Deno module states `v1.3.0` as the latest version when it's supposed to be `v1.4.1`. I feel like the issue was something about automation.
